### ISSUE TITLE
🎁: PBI wrapper - Custom Access denied message

### ISSUE THREAD

**Issue by atlewee** [equinor/fusion-workspace#551] opened 2023-12-05 09:45 UTC
## Expected outcome

The user is presented with how to get access

## Business Value / Developer Experience

Today, when you get an access denied error the user does not know how to obtain access.
Telling the user where to apply for access will make the process more efficient and a lot less frustrating

## Acceptance Criteria

- [ ] Report-apps can provide a custom "access-denied" error message that the wrapper displays if has problems getting the report token.

**Comment by JoneUE** [comment] 2024-01-19 12:47
Duplicate of this https://github.com/orgs/equinor/projects/415/views/2?pane=issue&itemId=46615431

**Comment by ken-mellem** [comment] 2024-01-19 14:21
This cannot be In progress without any assigned - automation kicked in.... We chose to load the previous app with the previous loader. This will not be possible until Core finishes their new loader - and that is not ready and currently not highest in priority.

**Comment by JoneUE** [comment] 2024-01-19 15:11
Seem that there was an automated job that put it to in progress

**Comment by ken-mellem** [comment] 2024-01-25 09:17
Apparently, I have misunderstood something.

## Reproduced
When the user does not have access the following is displayed
![image](https://github.com/equinor/fusion-workspace/assets/110427825/918100c2-2bbb-4046-b7f3-b05a817b5520)

## Wanted (as in Fusion)

![image](https://github.com/equinor/fusion-workspace/assets/110427825/9120856b-09b7-4a44-9c03-d814b855cd59)

## Note

It appears we are not giving correct message to the user when they do not have access for reports when loading workspace reports or report apps. This should come from the report admin in Fusion.

**Comment by ken-mellem** [comment] 2024-01-25 10:33
@Gustav-Eikaas informs me that there is a bug in Fusion Core. They are on it.

**Comment by Gustav-Eikaas** [comment] 2024-01-26 12:58
ADS-engineering-meeting
Troll west electrification
RLS seems to be working now but some bug in frontend makes it show "failed to load report" instead of rls config

**Comment by Gustav-Eikaas** [comment] 2024-01-26 13:10
After fix it looks like this. We can build what Fusion has with pictures and everything but we do not have any implementation right now. Should we prioritize making an informative error message?
![image](https://github.com/equinor/fusion-workspace/assets/89254170/8b199759-36ac-486a-8b59-f592ea308982)

**Comment by ken-mellem** [comment] 2024-01-26 13:28
At least it says "No access"... that must be MVP... let's accept that for the time being.

**Comment by Htonning** [comment] 2024-01-31 09:12
Does the closing of this mean that users now see a a text that we can customize per report? If not I would like to keep this issue open and in the backlog, because we really want this in the future. With more reports in the project portal that has different access control, we need to be able to guide users that dont have access on how they should proceed to get access.

**Comment by ken-mellem** [comment] 2024-01-31 14:56
@Htonning sure - I'll see what we can accomplish.

**Comment by Htonning** [comment] 2024-02-01 06:49
We also have some examples of users that are confused regarding the access management, attaching a screenshot of an email to show why it is important that users get good guidance by the project portal instead of having to send emails to Per Kristian to figure out how it works:

![image](https://github.com/equinor/fusion-workspace/assets/95220958/700e4636-6a6e-43ef-8347-6a6e7099362f)

**Comment by ken-mellem** [comment] 2024-02-09 10:56
@kjellhaaland I think this one you could take on Monday.

**Comment by kjellhaaland** [comment] 2024-02-09 12:47
Some links that may be useful:
- https://fusion.equinor.com/apps/financial-mandate-dashboard/
- https://github.com/equinor/fusion-components/blob/c27e10ef81bea898a7d2134bdfb7f3197892f608/src/components/data/PowerBI/ReportInfo/PowerBIReportInfo.tsx#L25

**Comment by kjellhaaland** [comment] 2024-02-13 14:35
I have implemented a error message component for displaying this information and made a PR for fusion-workspace.
When the PR is approved, i will make a PR for cc-reports, to include it in reports.

@ken-mellem / @Htonning, can you verify that this looks like you want?

@lindayd, some of the reports i have used for testing is missing a _description_ and _accessdescription_. This dialog will be most useful if these was present. Is there any future plan on adding such descriptions to the reports?

**The dialog shows:**

1. The _Access Description_ for the report
2. The general _Description_ for the report
3. The Owner of the report
4. The raw _Row level security requirements_

Screenshot:
![Image](https://github.com/equinor/fusion-workspace/assets/17578087/3b3765ec-2d8a-412c-bb18-348826d4cf37)

**Comment by lindayd** [comment] 2024-02-13 15:29
@kjellhaaland I will add some more useful information in the description fields for the reports tomorrow.

**Comment by lindayd** [comment] 2024-02-14 08:24
@kjellhaaland I have added some information in the description fields in CI for all ADS reports for testing.

**Comment by kjellhaaland** [comment] 2024-02-16 09:12
This is now ready for test.
Currently only implemented in cc-reports, but i am working on implementing it in cc-components as well.

Not sure who is the right person to test and verify.

@ken-mellem @atlewee @lindayd @Htonning ? 😃 

[Link to test](https://webserver-fusion-project-portal-test.radix.equinor.com/apps/ads-engineering-meeting/17ea3570-24a6-445f-8948-b08240d0db87?tab=powerbi)

**Comment by ken-mellem** [comment] 2024-02-16 11:59
I have access - but got help.

Looks good! Add scrollbar - when expanding the extra information section, you cannot read all without zooming out.

**Comment by ken-mellem** [comment] 2024-02-16 12:00
@Htonning I assume you have access ;)

**Comment by lindayd** [comment] 2024-02-16 12:30
@kjellhaaland @ken-mellem Looks good! No other comments except the one Ken already mentioned regarding the Access control description section.

**Comment by kjellhaaland** [comment] 2024-02-19 08:31
Added scrollbar in latest PR. 
Waiting for code-review before merging to prod in both cc-applications and cc-reports.

**Closed** 2024-02-20 09:21 UTC
Labels: feature, Core
